option(GCOVR "use gcovr for code coverage, if available" OFF)

if (GCOVR)
    find_program(GCOVR_EXEC "gcovr")
    if(GCOVR_EXEC)
        message(STATUS "Using gcovr")
        include(${PROJECT_SOURCE_DIR}/cmake/tools/test_helper.cmake)
        string(REPLACE " " "%20" url_root_path "${CMAKE_BINARY_DIR}")
        if (CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|Intel")
            add_compile_options(-fprofile-arcs -ftest-coverage)
            add_link_options(-fprofile-arcs -ftest-coverage)
        endif()
        add_custom_target(gcovr_coverage COMMAND "${GCOVR_EXEC}" -r "${PROJECT_SOURCE_DIR}" . && "${GCOVR_EXEC}" -r "${PROJECT_SOURCE_DIR}" . --html --html-details -o ./cov/index.html && echo "HTML Summary: file://${url_root_path}/cov/index.html")
        add_dependencies(run_coverage gcovr_coverage)
    else()
        message(WARNING "Requested gcovr, but it was not found. Continuing without it...")
    endif()
endif()
