option(INCLUDE_WHAT_YOU_USE "use Include-what-you-use while compiling, if available" OFF)

if (INCLUDE_WHAT_YOU_USE)
	find_program(INCLUDE_WHAT_YOU_USE_EXEC "include-what-you-use")
	if(INCLUDE_WHAT_YOU_USE_EXEC)
		message(STATUS "Using Include-what-you-use")
	  set(CMAKE_CXX_CPPCHECK ${INCLUDE_WHAT_YOU_USE_EXEC})
	else()
		message(WARNING "Requested Include-what-you-use, but it was not found. Continuing without it.")
	endif()
endif()
