include(${PROJECT_SOURCE_DIR}/cmake/tools/asan.cmake)
include(${PROJECT_SOURCE_DIR}/cmake/tools/catch2.cmake)
include(${PROJECT_SOURCE_DIR}/cmake/tools/clang_tidy.cmake)
include(${PROJECT_SOURCE_DIR}/cmake/tools/conan.cmake)
include(${PROJECT_SOURCE_DIR}/cmake/tools/cppcheck.cmake)
include(${PROJECT_SOURCE_DIR}/cmake/tools/gtest.cmake)
include(${PROJECT_SOURCE_DIR}/cmake/tools/include_what_you_use.cmake)
include(${PROJECT_SOURCE_DIR}/cmake/tools/vcpkg.cmake)
